### ISSUE TITLE
angular2 出了咋办呢

### ISSUE THREAD

**Issue by huobazi** [ruby-china/ruby-china-app#1]
我看到用的是 1.4 ，那 angular2 出了咋办呢

**Comment by huobazi** [comment]
哇， issues/1 啊

**Comment by DotHide** [comment]
@huobazi 暂时还没来得及考虑升2.0的问题，如果够用何必一味追求最新，我觉得技术更新换代是有过程和条件的，一是看是否适应生产力的需要，二还得看新技术本身的兼容能力，到该升得时候照样得升，可以应付的时候就先把业务做精吧。😬
