### ISSUE TITLE
下拉选择节点，选择以后应该是替换前面“话题节点”几个字

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-app#11]
<img width="498" alt="2015-11-20 10 00 24" src="https://cloud.githubusercontent.com/assets/5518/11290033/93f1d0c0-8f6d-11e5-93b0-54190d2d2566.png">

**Comment by DotHide** [comment]
已修改 https://github.com/ruby-china/ruby-china-app/commit/e17f3f9bce8e0106be9629ad3f1a3cdbf628c263
