### ISSUE TITLE
请问是否可以支持iPad?

### ISSUE THREAD

**Issue by stardiviner** [ruby-china/ruby-china-app#16]
如题

**Comment by jasl** [comment]
ionic写的，本身是全平台兼容，不过非手机设备的话，因为UI没优化，所以效果会怪怪的

**Comment by stardiviner** [comment]
测试了，在ipad侠就是普通的全平台app那样，UI需要缩小，1x大小。用着确实怪怪的。
是否需要关闭这个issue？

**Comment by jasl** [comment]
关了吧，看看以后有没有计划能够制作一个平板版本的布局~
