### ISSUE TITLE
Back navigation not working 

### ISSUE THREAD

**Issue by genkio** [ruby-china/ruby-china-app#17]
iOS 9.2.1
不知道是不是打开链接的姿势不对，打开任何（论坛以外的）链接后，没有返回键，也不支持滑动返回，就停在当前页面没辙了...

**Comment by huacnlee** [comment]
没实现

**Comment by DotHide** [comment]
Resolved! https://github.com/ruby-china/ruby-china-app/commit/71226921880a13d2c9d3245c02f89f0ca5625fe0
