### ISSUE TITLE
使用 Material Design 主题

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-app#2]
http://ionicmaterial.com/

**Comment by DotHide** [comment]
@huacnlee 好的，明白

**Comment by huacnlee** [comment]
目测很快就能 Release 1.0 版本了

**Comment by DotHide** [comment]
API还要再完善一下，现在发现缺少用户修改资料、修改密码等，还有上次发你邮箱的一些参数

**Comment by huacnlee** [comment]
@DotHide 重新列一下，在 ruby-china/ruby-china 项目里面开 Issue，描述需要的详细字段

**Comment by DotHide** [comment]
我看了一下 Material Design，直接套界面有点乱，细节还要再处理，你觉得这一版就一定要上这个主题吗？还是放到后面一版再加，甚至可以做成让用户自己选择主题呢？

**Comment by chloerei** [comment]
我觉得 iOS 用苹果风格，Android 用 Material Design，不要让用户选择。

**Comment by huacnlee** [comment]
就一个，其实目前 Ruby China 就有点基于那个的，这边你别管，我来处理 UI 的细节，你搞功能吧

**Comment by huobazi** [comment]
MSUI 也不错的

http://m.sui.taobao.org/
http://framework7.taobao.org/

**Comment by DotHide** [comment]
这个可以关闭了
