### ISSUE TITLE
以 Ruby China 的身份注册 Apple ID 用于发布 iOS 应用

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-app#3]
@lgn21st @jasl 是否还有费用

**Comment by jasl** [comment]
应该有富余的，不过我首先要把我欠别人的钱，别人欠我的钱理清以后，再去做最后的收支计算

-- 
Hotmail
Sent with Airmail

在 October 14, 2015 11:34:19, Jason Lee (notifications@github.com) 写到:

@lgn21st @jasl 是否还有费用

**Comment by jasl** [comment]
需要多少钱？
我可以先转给你，按往年来看，应该有一点结余（我基本会在大会期间把钱尽量花掉）

**Comment by huacnlee** [comment]
<img width="935" alt="2015-10-14 11 58 07" src="https://cloud.githubusercontent.com/assets/5518/10474586/e63d19ea-726a-11e5-94d7-0fd6f3734540.png">

688 元 / 年

**Comment by huobazi** [comment]
要有官方 app 了 好开心 :+1:

**Comment by DotHide** [comment]
ID 现在有了吗？给我个证书，接下去要联机调试拉

**Comment by huacnlee** [comment]
还没，我昨天本来说去开通的，结果遇到奇怪的错误，流程走不下去

**Comment by DotHide** [comment]
这个现在怎么说？另外几个 Issue 怎么说？

**Comment by huacnlee** [comment]
我正在申请账号中，之前遇到无法申请成功的问题，在联系客服解决
Madz notifications@github.com于2015年11月24日 周二16:01写道：
