### ISSUE TITLE
会怎么考虑上传功能呢

### ISSUE THREAD

**Issue by huobazi** [ruby-china/ruby-china-app#4]
比如 图片

**Comment by huacnlee** [comment]
调用 Ruby China 的上传接口呀，不过上传前先裁剪优化一下尺寸，Ruby China 上面图片都会直接按最大 1280px 来缩小的

**Comment by huobazi** [comment]
个人一直觉得图片上传插入编辑器这块儿，应该是插入后转换为 图片显示，而不是 markdown 标记显示在那里，这点 知乎 的编辑框 做的就很棒。

**Comment by DotHide** [comment]
刚才我调用了一下 photos.json 接口，返回值总是："image_url": "photo/.jpg" 是不是有问题？我需要又拍云的地址，这样就跟网页插入图片一样了

**Comment by huacnlee** [comment]
是失败了

**Comment by DotHide** [comment]
file 格式有讲究吗？我传的是 data_url，类似这种
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHBvaW50ZXItZXZlbnRzPSJub25lIiB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHN0eWxlPSJ3aWR0aDogNTBweDsgaGVpZ2h0OiA1MHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMCwgMTM1LCAxOTEpOyI+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeT0iNTAlIiB4PSI1MCUiIGR5PSIwLjM1ZW0iIHBvaW50ZXItZXZlbnRzPSJhdXRvIiBmaWxsPSIjZmZmZmZmIiBmb250LWZhbWlseT0iSGVsdmV0aWNhTmV1ZS1MaWdodCxIZWx2ZXRpY2EgTmV1ZSBMaWdodCxIZWx2ZXRpY2EgTmV1ZSxIZWx2ZXRpY2EsIEFyaWFsLEx1Y2lkYSBHcmFuZGUsIHNhbnMtc2VyaWYiIHN0eWxlPSJmb250LXdlaWdodDogNDAwOyBmb250LXNpemU6IDMwcHg7Ij5SPC90ZXh0Pjwvc3ZnPg==

**Comment by huacnlee** [comment]
<img width="823" alt="2015-11-18 16 52 14" src="https://cloud.githubusercontent.com/assets/5518/11236459/c723d1a0-8e14-11e5-912e-2766463e474c.png">

你传的，失败了，空白的

**Comment by huacnlee** [comment]
HTTP Upload Multipart 的方式上传
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

**Comment by huacnlee** [comment]
这个应该不行的，要用 Multipart 的方式上传文件

## 

Jason Lee

在 2015年11月18日 星期三，16:49，Madz 写道：

**Comment by DotHide** [comment]
是用了 Multipart，难道是给参数的姿势不对？

> POST /api/v3/photos.json?access_token=d5fc83b30a0a481c78125048e5529e85b9f072c2657008a2b5151f22e54b8221 HTTP/1.1
> Content-Type: multipart/form-data; boundary=**X_PAW_BOUNDARY**
> Host: ruby-china.org
> Connection: close
> User-Agent: Paw/2.2.2 (Macintosh; OS X/10.11.1) GCDHTTPRequest
> Content-Length: 681

--**X_PAW_BOUNDARY**
Content-Disposition: form-data; name="file"

data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHBvaW50ZXItZXZlbnRzPSJub25lIiB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHN0eWxlPSJ3aWR0aDogNTBweDsgaGVpZ2h0OiA1MHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMCwgMTM1LCAxOTEpOyI+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeT0iNTAlIiB4PSI1MCUiIGR5PSIwLjM1ZW0iIHBvaW50ZXItZXZlbnRzPSJhdXRvIiBmaWxsPSIjZmZmZmZmIiBmb250LWZhbWlseT0iSGVsdmV0aWNhTmV1ZS1MaWdodCxIZWx2ZXRpY2EgTmV1ZSBMaWdodCxIZWx2ZXRpY2EgTmV1ZSxIZWx2ZXRpY2EsIEFyaWFsLEx1Y2lkYSBHcmFuZGUsIHNhbnMtc2VyaWYiIHN0eWxlPSJmb250LXdlaWdodDogNDAwOyBmb250LXNpemU6IDMwcHg7Ij5SPC90ZXh0Pjwvc3ZnPg==
--**X_PAW_BOUNDARY**--

**Comment by huacnlee** [comment]
你可以尝试构造一个简单的 Form 表单提交试试

**Comment by huacnlee** [comment]
<img width="1077" alt="2015-11-18 17 05 48" src="https://cloud.githubusercontent.com/assets/5518/11236757/a627d3d2-8e16-11e5-8df4-e37a4a48a192.png">

我刚刚用同样的 access_token 用 Chrome 插件 Postman 测试通过

**Comment by DotHide** [comment]
Postman上OK了，但程序调了半天，后来一直报Image类型不对，原来是必须传文件名，后台文件类型是根据文件名后缀来判断的，现在解决了 😑

**Comment by huacnlee** [comment]
这里也正好提醒我修改说明

Madz notifications@github.com于2015年11月19日 周四09:06写道：
