### ISSUE TITLE
很多地方都在用 P，这是不对的，P 里面不能包含 P, Div 之类的东西

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-app#5]

**Comment by DotHide** [comment]
我一般是显示字段用到 p，里面放 span 控制左右浮动，要不全换成 div ？

**Comment by huacnlee** [comment]
这么记住，P 只用于正文

## 

Jason Lee

在 2015年10月15日 星期四，20:55，Madz 写道：

**Comment by huacnlee** [comment]
我在重新组织 HTML 和 CSS 结构  

## 

Jason Lee

在 2015年10月15日 星期四，20:55，Madz 写道：

**Comment by DotHide** [comment]
没弄懂哪些才是正文，正好学习一下你的结构

**Comment by huacnlee** [comment]
@DotHide 其他地方都不要用就对了，p 现在唯一的用处是在文章里面用于表示一个段落，比如 Markdown 转换出来的内容。

布局应该用 div, span 或其他的东西

**Comment by DotHide** [comment]
这下明白了。
