### ISSUE TITLE
主要的 nav-bar 上面怎么弄成 Ruby China（有颜色）的，不用每个页面都修改那个地方

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-app#6]
![fireshot capture 17 - ruby china - https___ruby-china org_topics](https://cloud.githubusercontent.com/assets/5518/10518661/09b0e1ba-7395-11e5-9efc-5627bcf36cba.png)

导航做成类似这样

另外注意右边显示通知图标

**Comment by DotHide** [comment]
https://github.com/ruby-china/ruby-china-app/commit/a52e1e633348732f3904a803ce6c5270cccc4a68
