### ISSUE TITLE
UI 设计稿，可以参考这个来作

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china-app#8]
https://ruby-china.org/topics/28050

**Comment by DotHide** [comment]
回来了，争取这周完成

**Comment by huobazi** [comment]
@DotHide  :kiss:

**Comment by huacnlee** [comment]
https://github.com/ruby-china/ruby-china-app-ui

原始设计稿

**Comment by DotHide** [comment]
重构了一个版本，原来那个 develop 分支弃用了，新开了个叫 develop_new

**Comment by DotHide** [comment]
Topic List 的倒三角是干什么？
Topic Detail 页面右上角的更多按钮是干嘛用？是否要暂时省去？User Profile 也是

**Comment by huacnlee** [comment]
Popup 菜单，里面包含其他一些次要功能，比如，修改，删除，NoPoint, 置顶，精华

**Comment by huacnlee** [comment]
神速，一晚上改这么多

**Comment by huacnlee** [comment]
个人 Profile, 发帖编辑，回复编辑等页面，图上左上角是 X 按钮的
应该是以 Popup Page 的方式打开，而不是像话题查看那样，所以那里交互应该是由下往上打开的，点关闭以后是往下收回去

**Comment by huacnlee** [comment]
用户头像你可以放心用 API 返回的头像地址，已经实现了设计稿风格的默认头像了

**Comment by DotHide** [comment]
个人Profile我试过了，那个方式有些困难，popup的page后面要再换路由页面很难控制（比如你可能会再Profile页面再点击收藏，这样页面会进入下一级，其实是路由变换），所以我觉得只有发帖，回帖，登录等这种即时性的页面可以做成Popup，你觉得呢？

**Comment by DotHide** [comment]
用户头像我这儿没问题，另外添加表情似乎用不到，手机键盘上有

**Comment by huacnlee** [comment]
表情可以下一版实现，先用系统的
这版本优先必要的功能
Madz notifications@github.com于2015年11月18日 周三14:26写道：

**Comment by huacnlee** [comment]
也可以  

## 

Jason Lee

在 2015年11月18日 星期三，14:24，Madz 写道：

**Comment by DotHide** [comment]
发布新话题做成这样如何？
<img src="https://cloud.githubusercontent.com/assets/1009741/11300885/761dc3f0-8fcd-11e5-9090-65fb915e06d3.png" alt="New Topic" style="width:320px;height:240px;">

**Comment by huacnlee** [comment]
挺好的！
Madz notifications@github.com于2015年11月20日 周五21:27写道：

**Comment by DotHide** [comment]
发布新话题页面，底部搞了半天，总算弄出来了，但实现方法还不算完美。
❗️这地方你改界面谨慎，部分代码依赖了界面样式，最终实现效果是类似新浪微博客户端的新建文字微博，但网上我没找到现成的，我后续打算专门做一个可复用的Note面板。

总结一下实现思路：
- 首先，“说点什么”是个大的textarea，根据设备大小初始化它的高度，使之铺满屏幕，因此点击屏幕空白出会使之获得焦点；
- 然后，“说点什么”获得焦点后，键盘会弹出，但会挡住底部的操作条，此时需要把底部操作条提上来，提到键盘高度（但点击“主题”和“话题节点不需要”）；
- 接着，“说点什么”离开焦点，操作条应该回到底部
- 最后也是最让人忽略的一点，当键盘弹出时，“说点什么”的高度也应变化，调整到键盘以上位置，使得输入不会超出可见范围。

**Comment by huacnlee** [comment]
好的
