### ISSUE TITLE
论坛似乎不能在 NoPoint 发新帖

### ISSUE THREAD

**Issue by DotHide** [ruby-china/ruby-china-app#9]
想搞个测试专用贴，不能在 NoPoint 发新帖，暂时在社区开发里建了

**Comment by huacnlee** [comment]
就发到社区开发里面吧，发送成功以后自行删除，你搞个测试账号，我开通权限

**Comment by DotHide** [comment]
我新建了个账号 rubychina_app，并新建了应用，到时正式发布时也可替换这个密钥

**Comment by huacnlee** [comment]
这个账号可以发帖了  

## 

Jason Lee

在 2015年11月19日 星期四，17:11，Madz 写道：

> rubychina_app
